import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import { pretendard } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pretendard.className} antialiased flex items-center justify-center`}
      >
        <Header />
        <div className="flex lg:hidden w-screen h-screen items-center justify-center text-center">
          화면 폭을 넓혀 주세요! <br/>또는 아래에서 pdf로 저장하기
        </div>
        <div className="hidden lg:block w-screen h-screen px-4 pt-10 overflow-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}
