import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex items-center justify-center`}
      >
        <Header />
        <div className="flex lg:hidden w-screen h-screen items-center justify-center text-center">
          화면 폭을 넓혀 주세요! <br/>또는 아래에서 pdf로 저장하기
        </div>
        <div className="hidden lg:block w-screen h-screen p-4 pt-10 pb-18 overflow-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}
